version: '3'
# reference: https://www.emqx.com/en/blog/how-to-use-mqtt-in-nodejs
services:
  emqx1:
    image: emqx/emqx-enterprise:6.2.2
    container_name: emqx1
    environment:
    - "EMQX_NODE_NAME=emqx@node1.emqx.com"
    - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.com,emqx@node2.emqx.com]"
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      emqx-bridge:
        aliases:
        - node1.emqx.com
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083
    volumes:
      - $PWD/emqx1_data:/opt/emqx/data


  # reference: https://oneuptime.com/blog/post/2026-02-08-how-to-run-timescaledb-in-docker-with-hypertables/view
  timescaledb:
    image: timescale/timescaledb-ha:pg18
    container_name: timescaledb
    restart: unless-stopped
    ports:
      - "6543:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # Disable TimescaleDB telemetry
      TIMESCALEDB_TELEMETRY: "off"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tsadmin -d tsdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "2.0"
volumes:
  timescaledb_data:
    driver: local
  # emqx2:
  #   image: emqx/emqx-enterprise:6.2.2
  #   container_name: emqx2
  #   environment:
  #   - "EMQX_NODE_NAME=emqx@node2.emqx.com"
  #   - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
  #   - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.com,emqx@node2.emqx.com]"
  #   healthcheck:
  #     test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
  #     interval: 5s
  #     timeout: 25s
  #     retries: 5
  #   networks:
  #     emqx-bridge:
  #       aliases:
  #       - node2.emqx.com
    # volumes:
    #   - $PWD/emqx2_data:/opt/emqx/data

networks:
  emqx-bridge:
    driver: bridge

